export const Action_Types={
    ALLPRODUCTS: "ALLPRODUCTS",
    PRODUCTID: 'PRODUCTID',
    PRODUCTDETAILS:'PRODUCTDETAILS',
    ADDTOCART:'ADDTOCART',
    DELETEFROMCART:'DELETEFROMCART',
    INCREMENT:'INCREMENT',
    DECREMENT:'DECREMENT',
    CATEGORYSELECT:'CATEGORYSELECT',
    PRODUCTSBASEDONCATEGORY:'PRODUCTSBASEDONCATEGORY',
}